apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-call-infra
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Qu11et/video-call-web-argocd.git
    targetRevision: main
    path: infra
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: video-call-prod  # Deploy vào namespace riêng cho database
  
  syncPolicy: 
    automated:
      prune:  true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true