apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-call-livekit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Qu11et/video-call-web-gitops.git'
    targetRevision: main
    path: livekit
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: video-call-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true