apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-call-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'hhttps://github.com/Qu11et/video-call-web-argocd.git' # Thay link git của bạn
    targetRevision: main
    path: infra
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: video-call-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true