
apiVersion: v1
kind: Secret
metadata:
  name: video-call-secrets
  namespace: postgres-operator
type: Opaque
stringData:
  # PostgreSQL credentials
  DB_USERNAME: "zalando"
  DB_PASSWORD: "5Lszsi8kAcwVcVaHQt4KRd29DNpVRGkVH0biXxCjTXPyeGkIHYdnrAxp9nouaUhp"

  # MongoDB credentials (nếu sử dụng)
  MONGO_USERNAME: "root"
  MONGO_PASSWORD: "password123"

  # JWT Secret Key
  JWT_SECRET_KEY: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

  # Email credentials (Gmail App Password)
  EMAIL_USERNAME: "khautyler@gmail.com"
  EMAIL_PASSWORD: "rcmvqygmtbthlotz"

  # LiveKit credentials
  LIVEKIT_API_KEY: "devkey"
  LIVEKIT_API_SECRET: "my_super_secure_secret_key_for_dev_only_123"
