apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  labels:
    app: livekit
data:
  livekit.yaml: |
    port: 7880
    http_port: 7880
    rtc:
      port_range_start: 50000
      port_range_end: 60000
      use_external_ip: true # Bắt buộc khi dùng hostNetwork
    
    # Chúng ta sẽ cấu hình Redis qua Biến môi trường (Environment Variable)
    # để bảo mật hơn, nên ở đây để trống phần redis.
    logging:
      json: false
      level: info