# livekit/values.yaml

# Tên này PHẢI KHỚP với 'name' trong dependencies của Chart.yaml
livekit-server:

  # Cấu hình Key/Secret (Nguyên nhân gây lỗi của bạn là đây)
  keys:
    devkey: secret 

  # Cho phép Pod dùng mạng trực tiếp của Node
  hostNetwork: true

  # Cổng mạng
  port: 7880
  httpPort: 7880
  udp_port: 7882
  
  rtc:
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true 

  # Tắt Redis đi kèm
  redis:
    enabled: false

  # Kết nối tới Redis tự quản lý
  extraEnv:
    - name: REDIS_HOST
      value: "redis.video-call-prod.svc.cluster.local"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      value: "password123"
    - name: LIVEKIT_KEYS
      value: "devkey:secret"  

  service:
    type: ClusterIP